### ISSUE TITLE
Adding RMT support

### ISSUE THREAD

**Issue by lucastcox** [HarryVienna/ESP32-TMC2208-UART-Component#1]
First of all, thank you for taking the time to write and publish this. It's saved me hours implementing the same driver myself. 

Currently, the driver is not very RTOS-friendly since it simply delays microseconds for each step. That results in 100% cpu being used on whichever core the task is scheduled on since it doesn't yield while waiting for each step pulse to complete.

Two possible solutions:

1. Add support for a high-resolution timer that gives a semaphore after a specified delay. Then, the task can yield until the semaphore is given, take the semaphore, then repeat.
2. Add support for using the RMT peripheral to generate the step pulses. Then, the task can yield until all pulses complete

Let me know if you'd like me to open a PR with either of those changes. I might also throw in some "extern "C" blocks in the header files to avoid linking issues when mixed with cpp code.

**Comment by HarryVienna** [comment]
Thank you very much for your comment!

On my [website ](https://www.haraldkreuzer.net/en/news/esp32-library-trinamic-tmc2208-stepper-motor-driver)I wrote already about this topic:

`Another important function is moving the stepper motor, which is done by pulses on the STEP line of the TCM2208. Unfortunately, the ESP32 does not provide a function to generate a given number of pulses. Only with the ESP32-S2, ESP32-C3 and ESP32-S3 it would be possible to send a certain sequence of signals via the RMT (Remote Control) module. Therefore, the generation of the pulses is done via a simple loop with a defined delay between the pulses. It would also be possible to connect the STEP pulse output signal to an input pin on the ESP32. The LED control (LEDC) module would generate the pulses and with the PCNT (Pulse Counter) module the LEDC module would have to be stopped again in an interrupt after a defined number of pulses. Maybe I will include this in a future version, because this solution would reduce the CPU load significantly.
`

I use my driver to control a clock. Therefore i need to generate an exact number of pulses. So far I thought it is not possible to do this with the basic ESP32 without a backchannel to count the pulses.  For newer models there is even a [lib from Espressif](https://github.com/espressif/esp-idf/tree/release/v4.4/examples/peripherals/rmt/step_motor) on GitHub that uses RMT.

I am very interested in how you solved this problem! I did already implement a version with LEDC and PCNT but did not use it so far because I don't like the solution that I need an additional pin of the ESP32 for counting pulses. And of course improving my C code is always welcome. I have to admit that this was one of my first C programs ever. I tried to follow the pattern how Espressif develops their components for ESP32.

**Comment by lucastcox** [comment]
The rmt peripheral allows you to send an exact pulse count with precise timing on both high and low times. Snippet attached below. Taken from a wrapper class I made for some basic rmt functionality. This is a janky heap-using c++ implementation, but it would be super easy to add to your implementation as well. Note that per

```cpp

ErrorCode EspRmt::SendPulses(size_t pulseCount)
{
    rmt_item32_t item{};
    item.duration0 = 40; //duration is specified in "ticks". Ticklength can be configured by setting up the rmt clock
    item.duration1 = 40;
    item.level0 = 1;
    item.level1 = 0;

    //todo: sanity check pulse count to avoid blowing the heap
    //todo: stop using the heap for something so repetitive to decrease fragmentation risk
    std::vector<rmt_item32_t> items;
    items.insert(items.begin(), pulseCount, item);
    //last argument set to "true" so that the task will yield until the entire transaction is complete. This will free up any other tasks
    MakeSureGood(rmt_write_items(mChannel, &items.at(0), pulseCount, true));
    return ErrorCode::Success;
}

ErrorCode EspRmt::Init()
{
    ErrorCode error{ErrorCode::Success};
    rmt_config_t conf = RMT_DEFAULT_CONFIG_TX(mPin, mChannel);
    MakeSureGood(rmt_config(&conf));
    MakeSureGood(rmt_driver_install(conf.channel, 0, 0));
    return error;
}
```

**Comment by lucastcox** [comment]
Sorry, to clarify: you *can* use the RMT peripheral on the esp32. I am currently using it on the esp32 (non-s2, etc). The base esp32 doesn't support looping a set number of times, but you can get around this by supplying multiple samples to it instead.

OR, you could just call rmt_write_items in a for loop one-at-a-time. 

For example:

```cpp
ErrorCode EspRmt::SendPulses(size_t pulseCount)
{
    rmt_item32_t item{};
    item.duration0 = 40;
    item.duration1 = 40;
    item.level0 = 1;
    item.level1 = 0;
    for (auto i = 0; i < pulseCount; i++)
    {
        MakeSureGood(rmt_write_items(mChannel, &item, 1, true));
    }
    return ErrorCode::Success;
}
```

This is still much better than using blocking waits since it will yield until the pulse finishes and then return if there is no other higher-priority task running. I was able to run two on the same thread easily using the loop method along with wifi +websockets and other tasks on the same core.

**Comment by lucastcox** [comment]
I'll submit a PR when I get a chance that implements the rmt peripheral. I'll try to add support for multiple rmt methods with it. It could be a couple of weeks before I get some time to back-port it to your library. Again, really appreciate the effort you put into this library. Saved me a *ton* of time.

**Comment by HarryVienna** [comment]
Thank you very much for this hint. I will try the rmt_write_items function as soon as I have a free ESP32. Currently they are all used by another project. And I am looking forward to your PR!

**Comment by HarryVienna** [comment]
I just committed some changes. Now I use RMT for generating the steps. I don't use a loop around rmt_write_items but generate an array of rmt_item32_t  items that will be send.

**Comment by lucastcox** [comment]
That looks great! Thanks very much. Sorry that I hadn’t done my PR. I haven’t had a lull in work yet to do it, but your implementation looks really good.

**Comment by HarryVienna** [comment]
Thanks!

So I can close my first issue :-)
